# .github/workflows/azure.yml
name: Build and Deploy to Azure

on:
  push:
    branches:
      - beastx

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Login to Azure Container Registry
        run: |
          az acr login --name f2aprod

      - name: Build and Push Docker Image
        run: |
          docker build -t f2aprod.azurecr.io/f2a-resume:${{ github.sha }} .
          docker push f2aprod.azurecr.io/f2a-resume:${{ github.sha }}

      